---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app
  namespace: default
  annotations:
    # TODO: replace RoleARN with real value from TF outputs
    eks.amazonaws.com/role-arn: RoleARN
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-test
  namespace: default
spec:
  serviceAccountName: my-app
  containers:
    - name: my-app-test
      image: amazon/aws-cli:latest
      # Sleep so that the container stays alive
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 5; done;"]